Support for kernel upstart scripts and better removal of extra modules

diff --git a/support/kernel.postinst b/support/kernel.postinst
--- a/support/kernel.postinst
+++ b/support/kernel.postinst
@@ -2,6 +2,7 @@
 
 PID=
 FORCE_INSTALL=
+UPSTART_SCRIPT=%UPSTART_SCRIPT%
 
 # Handle execution as pmPostInstall.script
 if [ -z "$IPKG_OFFLINE_ROOT" ]; then
@@ -90,6 +91,22 @@ for file in `find boot lib/modules -type f -print` ; do
     [ ! -f /$file ] || [ -w /$file ]	|| { echo "Unable to write to /$file"			; error=1 ; }
 done
 
+# Make sure the upstart script is writeable
+if [ -n "${UPSTART_SCRIPT}" ] ; then
+    echo "Verifying ability to create upstart script ..."
+    dir=var/palm/event.d
+    mkdir -p /$dir			|| { echo "Error creating /$dir"			; error=1 ; }
+    rm -f /$dir/.webosinternals.org ]	|| { echo "Error removing /$dir/.webosinternals.org"	; error=1 ; }
+    [ ! -f /$dir/.webosinternals.org ]	|| { echo "Unable to remove /$dir/.webosinternals.org"	; error=1 ; }
+    touch /$dir/.webosinternals.org ]	|| { echo "Error touching /$dir/.webosinternals.org"	; error=1 ; }
+    [ -f /$dir/.webosinternals.org ]	|| { echo "Unable to touch /$dir/.webosinternals.org"	; error=1 ; }
+    rm -f /$dir/.webosinternals.org ]	|| { echo "Error removing /$dir/.webosinternals.org"	; error=1 ; }
+    [ ! -f /$dir/.webosinternals.org ]	|| { echo "Unable to remove /$dir/.webosinternals.org"	; error=1 ; }
+    file=$dir/${PID}
+    [ -r ${SRCDIR}/$file ]		|| { echo "Unable to read from ${SRCDIR}/$file"		; error=1 ; }
+    [ ! -f /$file ] || [ -w /$file ]	|| { echo "Unable to write to /$file"			; error=1 ; }
+fi
+
 if [ "${error}" = "1" ] ; then
     echo "Fatal error occurred, not installing files"
     exit 1
@@ -103,11 +120,23 @@ for file in `find boot lib/modules -type f -print` ; do
     cp ${SRCDIR}/$file /$file		|| { echo "Error installing /$file"			; error=1 ; }
     [ -f /$file ]			|| { echo "Unable to install /$file"			; error=1 ; }
     cmp ${SRCDIR}/$file /$file		|| { echo "Unable to verify /$file"			; error=1 ; }
-    true
 done
+
+# Copy the upstart script to the target location
+if [ -n "${UPSTART_SCRIPT}" ] ; then
+    echo "Installing kernel upstart script ..."
+    file=var/palm/event.d/${PID}
+    rm -f /$file			|| { echo "Error removing /$file"			; error=1 ; }
+    [ ! -f /$file ]			|| { echo "Unable to remove /$file"			; error=1 ; }
+    cp ${SRCDIR}/$file /$file		|| { echo "Error installing /$file"			; error=1 ; }
+    [ -f /$file ]			|| { echo "Unable to install /$file"			; error=1 ; }
+    cmp ${SRCDIR}/$file /$file		|| { echo "Unable to verify /$file"			; error=1 ; }
+fi
 
 if [ "${error}" = "1" ] ; then
     echo "Fatal error occurred, restoring original files"
+    rm -f /var/palm/event.d/${PID}
+    rm -rf /lib/modules/`uname -r`/extra
     tar -C / -zxf ${APPS}/usr/palm/applications/${PID}/backup.tar.gz || \
 	{ echo "Fatal error occurred, unable to extract tarball" ; exit 1 ; }
     tar -C / -zdf ${APPS}/usr/palm/applications/${PID}/backup.tar.gz || \
