Optware bootstrap 1.6.0

diff --git a/testing-optware/bootstrap/control/postinst b/testing-optware/bootstrap/control/postinst
--- a/testing-optware/bootstrap/control/postinst
+++ b/testing-optware/bootstrap/control/postinst
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-PID="org.webosinternals.optware"
+APPID=org.webosinternals.optware
 
 # Handle execution as pmPostInstall.script
 if [ -z "$IPKG_OFFLINE_ROOT" ]; then
@@ -11,37 +11,44 @@ APPS=/media/cryptofs/apps
 
 [ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }
 
+APPDIR=${APPS}/usr/palm/applications/${APPID}
+
 # Stop the service if running
-/sbin/stop ${PID} || true
+/sbin/stop ${APPID} || true
 
 # Remove the upstart script
-rm -f /etc/event.d/${PID} /var/palm/event.d/${PID}
+rm -f /etc/event.d/${APPID} /var/palm/event.d/${APPID}
 
 # Remove the profile script
-rm -f /etc/profile.d/optware /etc/profile.d/${PID}
+rm -f /etc/profile.d/optware /etc/profile.d/${APPID}
 
-# Migrate legacy /media/internal/.optware/optware.ext3 to /media/cryptofs
-if [ -f /media/internal/.optware/optware.ext3 ] ; then
-    /bin/mv /media/internal/.optware/optware.ext3 /media/cryptofs/
-    /bin/rmdir /media/internal/.optware
+# Create the /media/ext3fs/opt directory if it does not already exist
+if [ -e /media/ext3fs ] && [ ! -e /media/ext3fs/opt ] ; then
+    /bin/mkdir -p /media/ext3fs/opt || \
+	{ echo "ERROR: Cannot create /media/ext3fs/opt directory" ; exit 1 ; }
 fi
 
-# Create the filesystem if it does not already exist
-if [ ! -e /media/cryptofs/optware.ext3 ] ; then
+# Create the /media/cryptofs/optware.ext3 filesystem if it does not already exist
+if [ ! -e /media/ext3fs/opt ] && [ ! -e /media/cryptofs/optware.ext3 ] ; then
     /bin/mkdir -p /media/cryptofs || \
 	{ echo "ERROR: Cannot create /media/cryptofs directory" ; exit 1 ; }
-    echo "Creating 64MB optware filesystem ..."
-    /bin/dd if=/dev/zero of=/media/cryptofs/optware.ext3 bs=1024 count=65536 || \
+    echo "Creating 128MB optware filesystem ..."
+    /bin/dd if=/dev/zero of=/media/cryptofs/optware.ext3 bs=4096 count=32768 || \
 	{ echo "ERROR: Cannot initialise /media/cryptofs/optware.ext3 file" ; exit 1 ; }
     /sbin/mkfs.ext3 -F -L optware /media/cryptofs/optware.ext3 || \
 	{ echo "ERROR: Cannot make /media/cryptofs/optware.ext3 filesystem" ; exit 1 ; }
 fi
 
-# Remove any empty legacy installation directory
-rmdir /var/opt || true
+# Migrate legacy /var/opt installation directory to /media/ext3fs/opt
+if [ -d /var/opt ] && [ -e /media/ext3fs/opt ] ; then
+    /bin/cp -a /var/opt/* /media/ext3fs/opt/ || \
+	{ echo "ERROR: Error migrating /var/opt to /media/ext3fs/opt" ; exit 1 ; }
+    /bin/rm -rf /var/opt || \
+	{ echo "ERROR: Error removing legacy /var/opt" ; exit 1 ; }
+fi
 
-# Migrate legacy /var/opt installation directory to /opt
-if [ -d /var/opt ] ; then
+# Migrate legacy /var/opt installation directory to /media/cryptosfs/optware.ext3
+if [ -d /var/opt ] && [ -e /media/cryptofs/optware.ext3 ] ; then
     /bin/umount /opt || true
     /bin/mount /media/cryptofs/optware.ext3 /opt || \
 	{ echo "ERROR: Unable to mount /opt for migration" ; exit 1 ; }
@@ -55,13 +62,13 @@ fi
 
 # Install the profile script
 mkdir -p /etc/profile.d/
-cp $APPS/usr/palm/applications/${PID}/profile/${PID} /etc/profile.d/${PID}
+cp ${APPDIR}/profile/${APPID} /etc/profile.d/${APPID}
 
 # Install the upstart script
 mkdir -p /var/palm/event.d
-cp $APPS/usr/palm/applications/${PID}/upstart/${PID} /var/palm/event.d/${PID}
+cp ${APPDIR}/upstart/${APPID} /var/palm/event.d/${APPID}
 
-# Start ${PID}
-/sbin/start -n ${PID}
+# Start ${APPID}
+/sbin/start -n ${APPID}
 
 exit 0
