Added checks to autopatch to make sure IPKG_OFFLINE_ROOT is defined in the install scripts

diff --git a/autopatch/postinst b/autopatch/postinst
--- a/autopatch/postinst
+++ b/autopatch/postinst
@@ -1,6 +1,8 @@
 #!/bin/sh
+
 APP_DIR=
 PATCH_NAME=
+
 if [ -f "/media/cryptofs/apps/usr/bin/diffstat" ] ; then
   FILE_LIST=`/media/cryptofs/apps/usr/bin/diffstat -p1 -l $APP_DIR/$PATCH_NAME`
 else
@@ -11,12 +13,19 @@ if [ -f "/media/cryptofs/apps/usr/bin/patch" ] ; then
 else
   PATCH_EXEC=/var/usr/bin/patch
 fi
+
 PATCH_CONTROL_DIR=$IPKG_OFFLINE_ROOT/usr/lib/.webosinternals.patches
 
 do_failure() {
   ipkg -o $IPKG_OFFLINE_ROOT remove `basename $APP_DIR`
   exit 1
 }
+
+if [ "$IPKG_OFFLINE_ROOT" = "" ]
+then
+  echo "ERROR: IPKG_OFFLINE_ROOT must be supplied to the postinst"
+  exit 1
+fi
 
 if [ "$APP_DIR" = "" ] || [ "$PATCH_NAME" = "" ]
 then
diff --git a/autopatch/prerm b/autopatch/prerm
--- a/autopatch/prerm
+++ b/autopatch/prerm
@@ -1,6 +1,8 @@
 #!/bin/sh
+
 APP_DIR=
 PATCH_NAME=
+
 if [ -f "/media/cryptofs/apps/usr/bin/diffstat" ] ; then
   FILE_LIST=`/media/cryptofs/apps/usr/bin/diffstat -p1 -l $APP_DIR/$PATCH_NAME`
 else
@@ -11,11 +13,18 @@ if [ -f "/media/cryptofs/apps/usr/bin/patch" ] ; then
 else
   PATCH_EXEC=/var/usr/bin/patch
 fi
+
 PATCH_CONTROL_DIR=$IPKG_OFFLINE_ROOT/usr/lib/.webosinternals.patches
 
 do_failure() {
   exit 1
 }
+
+if [ "$IPKG_OFFLINE_ROOT" = "" ]
+then
+  echo "ERROR: IPKG_OFFLINE_ROOT must be supplied to the prerm"
+  exit 1
+fi
 
 if [ "$APP_DIR" = "" ] || [ "$PATCH_NAME" = "" ]
 then
