Change prerm to check for ota first before trying to -R a patch.  This is needed so that in the event that a webOS OTA update adds functionality of a certain patch we will not wrongly remove it. Bumped meta version to rebuild patches without version bumping for the user. Bumped GPS gsm patch

diff --git a/autopatch/prerm b/autopatch/prerm
--- a/autopatch/prerm
+++ b/autopatch/prerm
@@ -26,7 +26,7 @@ IPKG_INFO_DIR=/usr/lib/ipkg/info
 PATCH_CONTROL_DIR=/var/usr/lib/.webosinternals.patches
 PATCH_PACKAGES_LIST=/media/internal/.webosinternals.patches.packages
 PATCH_LOG=/media/internal/webos-patches.log
-VERSION=aupt-1
+VERSION=aupt-2
 
 do_failure() {
   echo "*** FAILED ***" >> $PATCH_LOG
@@ -70,6 +70,83 @@ remove_images() {
   fi
 }
 
+check_for_ota() {
+  echo "" >> $PATCH_LOG
+  echo "----------------------------------" >> $PATCH_LOG
+  echo "Checking md5sums" >> $PATCH_LOG
+  echo "----------------------------------" >> $PATCH_LOG
+
+  for i in $FILE_LIST
+  do
+    file=/$i
+    file_md5sum=""
+    orig_palm_md5sum=""
+    palm_md5sum=""
+
+    if [ -e $file ]
+    then
+      file_md5sum=`md5sum $file | awk '{print $1}'`
+    fi
+
+    if [ -e $APP_DIR/md5sums ]
+    then
+      orig_palm_md5sum=`grep -h $file $APP_DIR/md5sums | awk '{print $1}'`
+      echo "Palm md5sum when installed: $orig_palm_md5sum"
+    fi
+  
+    if [ -e $APP_DIR/package_list ]
+    then
+      for j in `cat $APP_DIR/package_list`
+      do
+        if [ "$palm_md5sum" = "" ]
+        then
+          echo "Getting md5sum from Palm package: $j" >> $PATCH_LOG
+          palm_md5sum=`grep -h $file $IPKG_INFO_DIR/$j.md5sums | awk '{print $1}'`
+          echo "  md5sum: $palm_md5sum" >> $PATCH_LOG
+        fi
+      done
+    fi
+
+    if [ "$palm_md5sum" = "" ] && \
+       [ "`grep $file $IPKG_OFFLINE_ROOT/usr/lib/ipkg/info/*.list`" = "" ]
+    then
+      echo "Check for md5sum in $IPKG_INFO_DIR"
+      palm_md5sum=`grep -h $file $IPKG_INFO_DIR/*md5sums | awk '{print $1}'`
+      echo "  md5sum: $palm_md5sum" >> $PATCH_LOG
+    fi
+
+    if [ "$palm_md5sum" = "$file_md5sum" ]
+    then
+      echo "  Existing file matches Palm md5sum: $file" >> $PATCH_LOG
+      echo "  Remove backup" >> $PATCH_LOG
+      rm -f $file.webosinternals.orig
+    elif [ "$palm_md5sum" != "$palm_orig_md5sum" ]
+    then
+      orig_md5sum=`md5sum $file.webosinternals.orig | awk '{print $1}'`
+      echo "  md5sum of Palm file has changed since installation, assuming OTA" >> $PATCH_LOG
+      if [ "$palm_md5sum" != "$orig_md5sum" ]
+      then
+        echo "  Remove backup" >> $PATCH_LOG
+        rm -f $file.webosinternals.orig
+      fi
+    else
+      if [ "$palm_md5sum" = "" ]
+      then
+        echo "  Found created file: $file" >> $PATCH_LOG
+        created_files="$created_files $file"
+      else
+        echo "  Found modified file: $file" >> $PATCH_LOG
+        found_modified=yes
+      fi
+    fi
+  done
+
+  if [ "$found_modified" = "" ]
+  then
+    echo "All of the files in the patch are already stock (most likely due to OTA update)" | tee -a $PATCH_LOG
+  fi
+}
+
 # MAIN
 if [ ! -e $PATCH_LOG ]
 then
@@ -107,105 +184,38 @@ then
   do_failure
 fi
 
-echo "" >> $PATCH_LOG
-echo "----------------------------------" >> $PATCH_LOG
-echo "Dry run patch attempt..." >> $PATCH_LOG
-echo "----------------------------------" >> $PATCH_LOG
-$PATCH_EXEC -R -p1 -d / --dry-run < ${APP_DIR}/$PATCH_NAME 2>&1 >> $PATCH_LOG
+check_for_ota
 
-if [ $? -ne 0 ]
+if [ "$found_modified" != "" ]
 then
   echo "" >> $PATCH_LOG
   echo "----------------------------------" >> $PATCH_LOG
-  echo "dry run failed, checking if applying entire patch would succeed" >> $PATCH_LOG
+  echo "Dry run patch attempt..." >> $PATCH_LOG
   echo "----------------------------------" >> $PATCH_LOG
-  $PATCH_EXEC -p1 -d / --dry-run < ${APP_DIR}/$PATCH_NAME 2>&1 >> $PATCH_LOG
+  $PATCH_EXEC -R -p1 -d / --dry-run < ${APP_DIR}/$PATCH_NAME 2>&1 >> $PATCH_LOG
 
   if [ $? -ne 0 ]
   then
     echo "" >> $PATCH_LOG
     echo "----------------------------------" >> $PATCH_LOG
-    echo "Applying entire patch would not succeed, checking md5sums" >> $PATCH_LOG
+    echo "dry run failed, checking if applying entire patch would succeed" >> $PATCH_LOG
     echo "----------------------------------" >> $PATCH_LOG
+    $PATCH_EXEC -p1 -d / --dry-run < ${APP_DIR}/$PATCH_NAME 2>&1 >> $PATCH_LOG
 
-    for i in $FILE_LIST
-    do
-      file=/$i
-      file_md5sum=""
-      orig_palm_md5sum=""
-      palm_md5sum=""
-
-      if [ -e $file ]
-      then
-        file_md5sum=`md5sum $file | awk '{print $1}'`
-      fi
-
-      if [ -e $APP_DIR/md5sums ]
-      then
-        orig_palm_md5sum=`grep -h $file $APP_DIR/md5sums | awk '{print $1}'`
-        echo "Palm md5sum when installed: $orig_palm_md5sum"
-      fi
-  
-      if [ -e $APP_DIR/package_list ]
-      then
-        for j in `cat $APP_DIR/package_list`
-        do
-          if [ "$palm_md5sum" = "" ]
-          then
-            echo "Getting md5sum from Palm package: $j" >> $PATCH_LOG
-            palm_md5sum=`grep -h $file $IPKG_INFO_DIR/$j.md5sums | awk '{print $1}'`
-            echo "  md5sum: $palm_md5sum" >> $PATCH_LOG
-          fi
-        done
-      fi
-
-      if [ "$palm_md5sum" = "" ] && \
-         [ "`grep $file $IPKG_OFFLINE_ROOT/usr/lib/ipkg/info/*.list`" = "" ]
-      then
-        echo "Check for md5sum in $IPKG_INFO_DIR"
-        palm_md5sum=`grep -h $file $IPKG_INFO_DIR/*md5sums | awk '{print $1}'`
-        echo "  md5sum: $palm_md5sum" >> $PATCH_LOG
-      fi
-
-      if [ "$palm_md5sum" = "$file_md5sum" ]
-      then
-        echo "  Existing file matches Palm md5sum: $file" >> $PATCH_LOG
-        echo "  Remove backup" >> $PATCH_LOG
-        rm -f $file.webosinternals.orig
-      elif [ "$palm_md5sum" != "$palm_orig_md5sum" ]
-      then
-        orig_md5sum=`md5sum $file.webosinternals.orig | awk '{print $1}'`
-        echo "  md5sum of Palm file has changed since installation, assuming OTA" >> $PATCH_LOG
-        if [ "$palm_md5sum" != "$orig_md5sum" ]
-        then
-          echo "  Remove backup" >> $PATCH_LOG
-          rm -f $file.webosinternals.orig
-        fi
-      else
-        if [ "$palm_md5sum" = "" ]
-        then
-          echo "  Found created file: $file" >> $PATCH_LOG
-          created_files="$created_files $file"
-        else
-          echo "  Found modified file: $file" >> $PATCH_LOG
-          found_modified=yes
-        fi
-      fi
-    done
-
-    [ "$found_modified" = "" ] || failed_remove
-
-    echo "All of the files in the patch are already stock (most likely due to OTA update)" | tee -a $PATCH_LOG
+    if [ $? -ne 0 ]
+    then
+      failed_remove
+    else
+      echo "Interestingly, the patch seems to already be unapplied" | tee -a $PATCH_LOG
+    fi
   else
-    echo "Interestingly, the patch seems to already be unapplied" | tee -a $PATCH_LOG
+    echo "" | tee -a $PATCH_LOG
+    echo "----------------------------------" | tee -a $PATCH_LOG
+    echo "Actually removing the patch!" | tee -a $PATCH_LOG
+    echo "----------------------------------" | tee -a $PATCH_LOG
+    remove_images
+    $PATCH_EXEC -R -p1 -d / --no-backup-if-mismatch < ${APP_DIR}/$PATCH_NAME 2>&1 | tee -a $PATCH_LOG
   fi
-else
-  echo "" | tee -a $PATCH_LOG
-  echo "----------------------------------" | tee -a $PATCH_LOG
-  echo "Actually removing the patch!" | tee -a $PATCH_LOG
-  echo "----------------------------------" | tee -a $PATCH_LOG
-  remove_images
-  $PATCH_EXEC -R -p1 -d / --no-backup-if-mismatch < ${APP_DIR}/$PATCH_NAME 2>&1 | tee -a $PATCH_LOG
 fi
 
 for i in $created_files
