Remove faulty dependency of VKB. Added IPKG_OFFLINE_ROOT to script not hardcoded to /var

diff --git a/linux/obsolete-virtual-keyboard/postinst b/linux/obsolete-virtual-keyboard/postinst
--- a/linux/obsolete-virtual-keyboard/postinst
+++ b/linux/obsolete-virtual-keyboard/postinst
@@ -1,15 +1,24 @@
 #!/bin/sh
 PACKAGE=org.webosinternals.virtual-keyboard
 
-rm -rf /usr/palm/frameworks/mojo/submissions/200.18/templates/kbselector
-rm -rf /usr/palm/frameworks/mojo/submissions/200.18/resources/*/kbchars*
-rm -f /usr/palm/frameworks/mojo/submissions/200.18/stylesheets/webos-internals-virtual-keyboard.css
-rm -rf /usr/palm/frameworks/mojo/submissions/200.47/templates/kbselector
-rm -rf /usr/palm/frameworks/mojo/submissions/200.47/resources/*/kbchars*
-rm -f /usr/palm/frameworks/mojo/submissions/200.47/stylesheets/webos-internals-virtual-keyboard.css
-rm -rf /usr/palm/frameworks/mojo/submissions/200.72/templates/kbselector
-rm -rf /usr/palm/frameworks/mojo/submissions/200.72/resources/*/kbchars*
-rm -f /usr/palm/frameworks/mojo/submissions/200.72/stylesheets/webos-internals-virtual-keyboard.css
+if [ "$IPKG_OFFLINE_ROOT" = "" ]
+then
+  echo "ERROR: IPKG_OFFLINE_ROOT must be supplied to the postinst"
+  exit 1
+fi
 
-ipkg -o /var remove $PACKAGE
+if [ "`ipkg -o $IPKG_OFFLINE_ROOT list_installed | awk '{print $1}' | grep ^org.webosinternals.patches.add-onscreen-keyboard$`" = "" ]
+then
+  rm -rf /usr/palm/frameworks/mojo/submissions/200.18/templates/kbselector
+  rm -rf /usr/palm/frameworks/mojo/submissions/200.18/resources/*/kbchars*
+  rm -f /usr/palm/frameworks/mojo/submissions/200.18/stylesheets/webos-internals-virtual-keyboard.css
+  rm -rf /usr/palm/frameworks/mojo/submissions/200.47/templates/kbselector
+  rm -rf /usr/palm/frameworks/mojo/submissions/200.47/resources/*/kbchars*
+  rm -f /usr/palm/frameworks/mojo/submissions/200.47/stylesheets/webos-internals-virtual-keyboard.css
+  rm -rf /usr/palm/frameworks/mojo/submissions/200.72/templates/kbselector
+  rm -rf /usr/palm/frameworks/mojo/submissions/200.72/resources/*/kbchars*
+  rm -f /usr/palm/frameworks/mojo/submissions/200.72/stylesheets/webos-internals-virtual-keyboard.css
+fi
+
+ipkg -o $IPKG_OFFLINE_ROOT remove $PACKAGE
 exit 0
